package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

const seedLen = 32 // ed25519 seed bytes

// EnsureCompanionKeys generates a private key for every companion that has
// none. Call before persisting a config so identities are pinned in it.
func (c *Config) EnsureCompanionKeys() error {
	for i := range c.Companions {
		if c.Companions[i].PrivateKey != "" {
			continue
		}
		seed := make([]byte, seedLen)
		if _, err := rand.Read(seed); err != nil {
			return fmt.Errorf("generating key for companion %q: %w", c.Companions[i].Name, err)
		}
		c.Companions[i].PrivateKey = hex.EncodeToString(seed)
		slog.Info("generated companion identity", "companion", c.Companions[i].Name)
	}
	return nil
}

// MigrateKeyFiles inlines legacy keyFile identities into PrivateKey when a
// file config is imported. Paths resolve relative to baseDir (the config
// file's directory). A missing file leaves PrivateKey empty — a fresh
// identity is generated by EnsureCompanionKeys.
func (c *Config) MigrateKeyFiles(baseDir string) error {
	for i := range c.Companions {
		comp := &c.Companions[i]
		if comp.PrivateKey != "" {
			comp.KeyFile = ""
			continue
		}

		keyFile := strings.TrimSpace(comp.KeyFile)
		if keyFile == "" {
			// Legacy default used by old binaries when keyFile was omitted.
			keyFile = strings.ToValidUTF8(comp.Name, "") + "_companion.key"
		}
		if !filepath.IsAbs(keyFile) {
			keyFile = filepath.Join(baseDir, keyFile)
		}

		data, err := os.ReadFile(keyFile)
		if err != nil {
			if os.IsNotExist(err) {
				slog.Warn("companion key file not found — a new identity will be generated",
					"companion", comp.Name, "keyFile", keyFile)
				comp.KeyFile = ""
				continue
			}
			return fmt.Errorf("companion %q: reading key file %s: %w", comp.Name, keyFile, err)
		}

		seedHex := strings.TrimSpace(string(data))
		if err := validateSeedHex(seedHex); err != nil {
			return fmt.Errorf("companion %q: key file %s: %w", comp.Name, keyFile, err)
		}
		comp.PrivateKey = seedHex
		comp.KeyFile = ""
		slog.Info("inlined companion key file into config", "companion", comp.Name, "keyFile", keyFile)
	}
	return nil
}

func validateSeedHex(s string) error {
	seed, err := hex.DecodeString(s)
	if err != nil {
		return fmt.Errorf("privateKey must be hex: %w", err)
	}
	if len(seed) != seedLen {
		return fmt.Errorf("privateKey must be %d hex chars (%d-byte ed25519 seed), got %d bytes", seedLen*2, seedLen, len(seed))
	}
	return nil
}
